config/routes.rb
Rails.application.routes.draw do
  resources :labsessions, only: [:new,:create,:destroy]

  get 'select_lab', to: 'labsessions#new', as: 'select_lab'
  get 'deselect', to:'labsessions#destroy', as: 'deselect'
  

  resources :lab_sessions, only: [:new, :create, :destroy]
  resources :lab_settings
  resources :bookings
  resources :labs
  resources :groups
  resources :sessions, only: [:new, :create, :destroy]
  
  get 'register', to: 'lab_sessions#new', as: 'register'
  resources :labs

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :users
  get 'home/index'
  get 'home/mylabs'  
  get 'home/mygroups'
  get 'home/labreg'

   root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Home</h1>
<%=link_to "My Labs", home_mylabs_path%><br/>
<%=link_to "My Groups", home_mygroups_path%><br/>
<%=link_to "Lab registration", home_labreg_path%><br/>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/labreg.html.erb
<h1>Lab Registration</h1>
<%=  form_for @lab %>
<div class="field">
    <%= lab=Lab.all   
       select_tag "Lab", options_from_collection_for_select(lab, 'id', 'name', selected = nil), :multiple => false %>
</div>

<div class="field">
	<%= label_tag :password%><br>
	<%= password_field_tag :password%>
</div>

<div class="actions">
		<%= submit_tag "register"%>
</div>

	<br/>
<%=link_to "Home", root_url%>
<p>Find me in app/views/home/labreg.html.erb</p>

app/views/home/mygroups.html.erb
<h1>My Groups</h1>
<%=link_to "Home", root_url%><br/>
<%= 
groups = Group.joins("join groups_users on groups.id = groups_users.group_id").where(["groups_users.user_id = ?", current_user])
select_tag "Groups", options_from_collection_for_select(groups, 'id', 'name', selected = nil), :multiple => false,:include_blank => true %>
<p>Find me in app/views/home/mygroups.html.erb</p>

app/views/home/mylabs.html.erb
<h1>My Labs</h1>
<%=link_to "Home", root_url%><br/>
<%= select_tag "labs", options_from_collection_for_select(Lab.all, 'id', 'name'), :multiple => false %>


<p>Find me in app/views/home/mylabs.html.erb</p>