config/routes.rb
Rails.application.routes.draw do
  resources :labsessions, only: [:new,:create,:destroy]

  get 'select_lab', to: 'labsessions#new', as: 'select_lab'
  get 'deselect', to:'labsessions#destroy', as: 'deselect'
  

  resources :lab_sessions, only: [:new, :create, :destroy]
  resources :lab_settings
  resources :bookings
  resources :labs
  resources :groups
  resources :sessions, only: [:new, :create, :destroy]
  
  get 'register', to: 'lab_sessions#new', as: 'register'
  resources :labs

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :users
  get 'home/index'
  get 'home/mylabs'  
  get 'home/mygroups'
  get 'home/labreg'

   root 'home#index'

end

app/models/lab.rb
class Lab < ActiveRecord::Base
  has_secure_password
  has_and_belongs_to_many :users
  has_and_belongs_to_many :groups
def to_s
  	"#{name}  "
  end
end

app/controllers/labs_controller.rb
class LabsController < ApplicationController
  before_action :set_lab, only: [:show, :edit, :update, :destroy]

  # GET /labs
  # GET /labs.json
  def index
    @labs = Lab.all
  end

  # GET /labs/1
  # GET /labs/1.json
  def show
  end

  # GET /labs/new
  def new
    @lab = Lab.new
  end

  # GET /labs/1/edit
  def edit
  end
  
  # POST /labs
  # POST /labs.json
  def create
    @lab = Lab.new(lab_params)
    @users=User.where(:id => params[:users_selection])
    #User.where(:id => current_user.id)
    #@users = User.where(:id => params[:users])
    @lab.users << @users 
    respond_to do |format|
      if @lab.save
        format.html { redirect_to @lab, notice: 'Lab was successfully created.' }
        format.json { render :show, status: :created, location: @lab }
      else
        format.html { render :new }
        format.json { render json: @lab.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /labs/1
  # PATCH/PUT /labs/1.json
  def update
    @lab = Lab.find(params[:id])
    @users=User.where(:id => params[:users_selection])
    @lab.users.destroy_all   #disassociate the already added organizers
    @lab.users << @users
    respond_to do |format|
      if @lab.update(lab_params)
        format.html { redirect_to @lab, notice: 'Lab was successfully updated.' }
        format.json { render :show, status: :ok, location: @lab }
      else
        format.html { render :edit }
        format.json { render json: @lab.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labs/1
  # DELETE /labs/1.json
  def destroy
    @lab.destroy
    respond_to do |format|
      format.html { redirect_to labs_url, notice: 'Lab was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lab
      @lab = Lab.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lab_params
      params.require(:lab).permit(:name, :password, :password_confirmation, :mingroup, :maxgroup)
    end
end

app/helpers/labs_helper.rb
module LabsHelper
end

app/views/labs/_form.html.erb
<%= form_for(@lab) do |f| %>
  <% if @lab.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lab.errors.count, "error") %> prohibited this lab from being saved:</h2>

      <ul>
      <% @lab.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :mingroup %><br>
    <%= f.number_field :mingroup %>
  </div>
  <div class="field">
    <%= f.label :maxgroup %><br>
    <%= f.number_field :maxgroup %>
  </div>


  <div class="field">
    <%= f.label :users %>
    <%= select_tag "users_selection", options_from_collection_for_select(User.all, 'id', 'email',@lab.users.map{ |j| j.id }), :multiple => true %>
 </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/labs/edit.html.erb
<h1>Editing Lab</h1>

<%= render 'form' %>

<%= link_to 'Show', @lab %> |
<%= link_to 'Back', labs_path %>

app/views/labs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Labs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Mingroup</th>
      <th>Maxgroup</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @labs.each do |lab| %>
      <tr>
        <td><%= lab.name %></td>
        <td><%= lab.mingroup %></td>
        <td><%= lab.maxgroup %></td>
        <td><%= link_to 'Show', lab %></td>
        <td><%= link_to 'Edit', edit_lab_path(lab) %></td>
        <td><%= link_to 'Destroy', lab, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lab', new_lab_path %>

app/views/labs/new.html.erb
<h1>New Lab</h1>

<%= render 'form' %>

<%= link_to 'Back', labs_path %>

app/views/labs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lab.name %>
</p>

<p>
  <strong>Mingroup:</strong>
  <%= @lab.mingroup %>
</p>

<p>
  <strong>Maxgroup:</strong>
  <%= @lab.maxgroup %>
</p>

<%= link_to 'Edit', edit_lab_path(@lab) %> |
<%= link_to 'Back', labs_path %>